// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: StarterUI

#include "ui.h"


// COMPONENT LabelCount

lv_obj_t *ui_LabelCount_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_LabelCount;
cui_LabelCount = lv_label_create(comp_parent);
lv_obj_set_width( cui_LabelCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelCount, -179 );
lv_obj_set_y( cui_LabelCount, 25 );
lv_obj_set_align( cui_LabelCount, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelCount,"0");
lv_obj_set_style_text_font(cui_LabelCount, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELCOUNT_NUM);
children[UI_COMP_LABELCOUNT_LABELCOUNT] = cui_LabelCount;
lv_obj_add_event_cb(cui_LabelCount, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_LabelCount, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_LabelCount_create_hook(cui_LabelCount);
return cui_LabelCount; 
}

